<?php
$plugin = array(
  'title' => t('Gaia B'),
  'icon' => 'gaia-b.png',
  'category' => t('Kpane'),
  'theme' => 'gaia-b',
  'css' => 'gaia-b.css',
  'regions' => array(
    'row1' => t('Row 1'),
    'cola1' => t('Column A1'),
    'cola2' => t('Column A2'),
    'row2' => t('Row 2'),
    'colb1' => t('Column B1'),
    'colb2' => t('Column B2'),
    'row3' => t('Row 3'),
  ),
);
